force-app/main/default/objects/Dynamic_Record_Search_Config__c/Dynamic_Record_Search_Config__c.object-meta.xml
<CustomObject>
    <description>Dynamic Record Search Config. This object is for ADMINS.</description>
    <label>Dynamic Record Search Config</label>
    <nameField>
        <displayFormat>DRS-{00000}</displayFormat>
        <label>Dynamic Record Search Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Record Search Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</description>
    <inlineHelpText>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</inlineHelpText>
    <label>Field List</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Object Name API for search.</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User which will have the access on and Fields</description>
    <inlineHelpText>User which will have the access on and Fields</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Dynamic_Record_Search_Config</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SearchRecordControllerTest.cls
@IsTest
private class SearchRecordControllerTest {

	@TestSetup
	static void createTestData(){
		List<Account> accountList = new List<Account> {
			new Account(
				Name = 'Test'
			),
			new Account(
				Name = 'R.R. Tax'
			)
		};
		insert accountList;
	}

	@IsTest
	static void testGetSearchableObjectList_withCreatingData_listOfDetailForObject() {
		//Given
		final String sobjectApiNames = 'Account';
		final String fieldApiNames = 'Name';
		insert new Dynamic_Record_Search_Config__c(
			Object_API_Name__c = sobjectApiNames,
			Field_List__c = fieldApiNames,
			User__c = UserInfo.getUserId()
		);

		// When
		List<SearchRecordController.Detail> detailList = SearchRecordController.getSearchableObjectList();

		// Then
		System.assertEquals(1, detailList.size());
		System.assertEquals('Account', detailList[0].label);
		System.assertEquals('Account', detailList[0].value);
	}

	@IsTest
	static void testGetFieldListBySObjectApiName_withoutCreatingData_throwException() {
		//Gien
		final String sobjectApiNames = 'Account';

		// When - Then
		try {
			List<SearchRecordController.Detail> detailList = SearchRecordController.getFieldListBySObjectApiName(sobjectApiNames);
			System.assert(false, 'Exception Expected');
		} catch(Exception exp) {

		}
	}

	@IsTest
	static void testGetFieldListBySObjectApiName_listOfDetailForField() {
		// Given
		final String sobjectApiName = 'Account';
		final String fieldApiNames = 'Name';
		insert new Dynamic_Record_Search_Config__c(
			Object_API_Name__c = sobjectApiName,
			Field_List__c = fieldApiNames,
			User__c = UserInfo.getUserId()
		);

		// When
		List<SearchRecordController.Detail> detailList = SearchRecordController.getFieldListBySObjectApiName(sobjectApiName);

		// Then
		System.assertEquals(1, detailList.size());
		System.assertEquals('Account Name', detailList[0].label);
		System.assertEquals('Name', detailList[0].value);
	}

	@IsTest
	static void testSelectBySearchTearmAndSearchField_allCorrectData_accountRecordList() {

		// Given
		final List<String> fieldApiNameList = new List<String> {
			'Name'
		};
		final String sObjectName = 'Account';
		final String searchField = 'Name';
		final String searchTerm = 'Test';

		// When
		List<SObject> resultDataList = SearchRecordController.selectBySearchTearmAndSearchField(
			sObjectName,
			searchTerm,
			searchField,
			fieldApiNameList
		);

		// Then
		List<Account> resultaccountDataList = (List<Account>)resultDataList;
		System.assertEquals(1, resultaccountDataList.size());
		System.assertEquals(searchTerm, resultaccountDataList[0].Name);
	}
}