force-app/main/default/objects/Dynamic_Record_Search_Config__c/Dynamic_Record_Search_Config__c.object-meta.xml
<CustomObject>
    <description>Dynamic Record Search Config. This object is for ADMINS.</description>
    <label>Dynamic Record Search Config</label>
    <nameField>
        <displayFormat>DRS-{00000}</displayFormat>
        <label>Dynamic Record Search Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Record Search Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</description>
    <inlineHelpText>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</inlineHelpText>
    <label>Field List</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Object Name API for search.</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User which will have the access on and Fields</description>
    <inlineHelpText>User which will have the access on and Fields</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Dynamic_Record_Search_Config</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DynamicRecordSearchConfigSelector.cls
public with sharing class DynamicRecordSearchConfigSelector {
	
	private static final String OBJECT_API_NAME = 'Dynamic_Record_Search_Config__c';
	private static final String QUERY_FROM_KEY = ' FROM ';
	private static final String QUERY_SELECT_KEY = 'SELECT ';
	private static final String QUERY_WHERE_KEY = ' WHERE ';

	private static final List<String> FILED_LIST = new List<String> {
		'Id',
		'Object_API_Name__c',
		'Field_List__c'
	};

	public static List<Dynamic_Record_Search_Config__c> getRecordsByUserId(Id userId) {
		if(userId == null) {
			return new List<Dynamic_Record_Search_Config__c>();
		}
		String whereClause = QUERY_WHERE_KEY + 'User__c =:userId';
		return Database.query(generateQuery(whereClause));
	}

	public static List<Dynamic_Record_Search_Config__c> getRecordsByUserIdAndObjectapiName(Id userId, String objectAPIName) {
		if(userId == null | String.isBlank(objectAPIName)) {
			return new List<Dynamic_Record_Search_Config__c>();
		}
		String whereClause = QUERY_WHERE_KEY + 'User__c =:userId AND Object_API_Name__c =:objectAPIName';
		return Database.query(generateQuery(whereClause));
	}

	@TestVisible
	private static String generateQuery(String whereClause) {
		String query = QUERY_SELECT_KEY + String.join(FILED_LIST, ',') + QUERY_FROM_KEY + OBJECT_API_NAME;
		if(String.isBlank(whereClause)) {
			return query;
		} else {
			return query + ' ' + whereClause;
		}
	}
}