force-app/main/default/objects/Dynamic_Record_Search_Config__c/Dynamic_Record_Search_Config__c.object-meta.xml
<CustomObject>
    <description>Dynamic Record Search Config. This object is for ADMINS.</description>
    <label>Dynamic Record Search Config</label>
    <nameField>
        <displayFormat>DRS-{00000}</displayFormat>
        <label>Dynamic Record Search Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Record Search Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</description>
    <inlineHelpText>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</inlineHelpText>
    <label>Field List</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Object Name API for search.</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User which will have the access on and Fields</description>
    <inlineHelpText>User which will have the access on and Fields</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Dynamic_Record_Search_Config</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DynamicRecordSearchConfigSelectorTest.cls
@IsTest
private class DynamicRecordSearchConfigSelectorTest {

	private static final Id USER_ID = UserInfo.getUserId();

	@TestSetup
	static void createTestData() {
		final String fieldListForAccount = 'Name';
		final String fieldListForContact = 'Name';

		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = new List<Dynamic_Record_Search_Config__c> {
			new Dynamic_Record_Search_Config__c(
				User__c = USER_ID,
				Object_API_Name__c = 'Account',
				Field_List__c = fieldListForAccount
			),new Dynamic_Record_Search_Config__c(
				User__c = USER_ID,
				Object_API_Name__c = 'Contact',
				Field_List__c = fieldListForContact
			)
		};
		insert dynamicRecordSearchConfigList;
	}

	@IsTest
	static void testGetRecordsByUserIdAndObjectapiName_currentUserId_returndynamicRecordSearchConfigRecord() {
		//When
		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserId(USER_ID);

		//Then
		System.assertEquals(2, dynamicRecordSearchConfigList.size());
	}

	@IsTest
	static void testGetRecordsByUserIdAndObjectapiName_currentUserIdasNull_returndynamicRecordSearchConfigRecordbalnkList() {
		//Given
		final Id userId = null;
		//When
		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserId(userId);

		//Then
		System.assertEquals(0, dynamicRecordSearchConfigList.size());
	}

	@IsTest
	static void testGetRecordsByUserId_currentUserIdAndObjectAPIName_returndynamicRecordSearchConfigRecord() {
		//Given
		final String objectAPIName = 'Contact';
		final String fieldAPINameList = 'Name';

		//When
		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserIdAndObjectapiName(
			USER_ID,
			objectAPIName
		);

		//Then
		System.assertEquals(1, dynamicRecordSearchConfigList.size());
		System.assertEquals(objectAPIName, dynamicRecordSearchConfigList[0].Object_API_Name__c);
		System.assertEquals(fieldAPINameList, dynamicRecordSearchConfigList[0].Field_List__c);
	}

	@IsTest
	static void testGetRecordsByUserId_currentUserIdAsNullAndObjectAPIName_returndynamicRecordSearchConfigRecordBlankList() {
		//Given
		final String objectAPIName = 'Contact';
		final Id userId = null;

		//When
		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserIdAndObjectapiName(
			userId,
			objectAPIName
		);

		//Then
		System.assertEquals(0, dynamicRecordSearchConfigList.size());
	}

	@IsTest
	static void testGetRecordsByUserId_currentUserIdAndObjectAPINameAsNull_returndynamicRecordSearchConfigRecordBlankList() {
		//Given
		final String objectAPIName = null;
		final String fieldAPINameList = 'Name';

		//When
		List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserIdAndObjectapiName(
			USER_ID,
			objectAPIName
		);

		//Then
		System.assertEquals(0, dynamicRecordSearchConfigList.size());
	}

	@IsTest
	static void testGenerateQuery_blankWhereClause_returnQueryWithoutWhereClause() {

		//Given
		final String emptyWhereClause = '';

		//When
		String query = DynamicRecordSearchConfigSelector.generateQuery(emptyWhereClause);

		//Then
		System.assertEquals(false, query.contains('WHERE'));
	}
}