force-app/main/default/objects/Dynamic_Record_Search_Config__c/Dynamic_Record_Search_Config__c.object-meta.xml
<CustomObject>
    <description>Dynamic Record Search Config. This object is for ADMINS.</description>
    <label>Dynamic Record Search Config</label>
    <nameField>
        <displayFormat>DRS-{00000}</displayFormat>
        <label>Dynamic Record Search Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Record Search Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</description>
    <inlineHelpText>Comma separated filed list of object mentioned in Object API Name. These filed will be used for show data and search</inlineHelpText>
    <label>Field List</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Record_Search_Config__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Object Name API for search.</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchRecordController.cls
public with sharing class SearchRecordController {

	private static final integer QUERY_LIMIT_FOR_SEARCH = 200;
	
	@AuraEnabled
	public static List<SearchRecordController.Detail> getSearchableObjectList(){
		try {
			List<String> apiNameList = new List<String>();
			List<SearchRecordController.Detail> fieldDetailList = new List<SearchRecordController.Detail>();
			List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserId(UserInfo.getUserId());
			for(Dynamic_Record_Search_Config__c dynamicRecordSearchConfig : dynamicRecordSearchConfigList) {
				if(dynamicRecordSearchConfig.Object_API_Name__c != null) {
					apiNameList.add(dynamicRecordSearchConfig.Object_API_Name__c);
				}
			}
			Map<String, String> objectLableByApiNameMap = ObjectService.getObjectLableByApiNameMapByAPINameList(apiNameList);
			for(String apiName : objectLableByApiNameMap.keyset()) {
				fieldDetailList.add(
					new SearchRecordController.Detail(
						objectLableByApiNameMap.get(apiName),
						apiName
					)
				);
			}
			return fieldDetailList;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static List<SearchRecordController.Detail> getFieldListBySObjectApiName(String sobjectApiName){
		try {
			List<String> apiNameList;
			List<SearchRecordController.Detail> fieldDetailList = new List<SearchRecordController.Detail>();
			List<Dynamic_Record_Search_Config__c> dynamicRecordSearchConfigList = DynamicRecordSearchConfigSelector.getRecordsByUserIdAndObjectapiName(UserInfo.getUserId(), sobjectApiName);
			apiNameList = dynamicRecordSearchConfigList[0].Field_List__c.split(',');
			Map<String, String> fieldLabelByApiNameMap = FieldService.getFieldLableByApiNameBySobjectNameAndFieldAPIList(sobjectApiName, apiNameList);
			fieldLabelByApiNameMap.remove('Id');
			for(String apiName : fieldLabelByApiNameMap.keyset()) {
				fieldDetailList.add(
					new SearchRecordController.Detail(
						fieldLabelByApiNameMap.get(apiName),
						apiName
					)
				);
			}
			return fieldDetailList;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static List<SObject> selectBySearchTearmAndSearchField(
		String sobjectName,
		String searchTerm,
		String searchField,
		List<String> fieldList
	) {
		return SObjectSelector.selectBySearchTearmAndSearchField(
			sobjectName,
			searchTerm,
			searchField,
			fieldList,
			QUERY_LIMIT_FOR_SEARCH
		);
	}

	public class Detail {

		public Detail(String label, String value) {
			this.label = label;
			this.value = value;
		}

		@AuraEnabled
		public String label {get; set;}

		@AuraEnabled
		public String value {get; set;}
	}
}